// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAulbLvSnDKkcw_wJyqTeiZV7rrghOm4gc',
    appId: '1:1047069542114:web:20db810334204793b740bb',
    messagingSenderId: '1047069542114',
    projectId: 'tezda-app-afolabi',
    authDomain: 'tezda-app-afolabi.firebaseapp.com',
    storageBucket: 'tezda-app-afolabi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdzvU0IoENZ1ewWqikUZWh_BzPVwv2qEM',
    appId: '1:1047069542114:android:3398cb0cf8134573b740bb',
    messagingSenderId: '1047069542114',
    projectId: 'tezda-app-afolabi',
    storageBucket: 'tezda-app-afolabi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChSXbaNbYK1f1I6gcwQYQH-uzXJTb8p8o',
    appId: '1:1047069542114:ios:c4a6125c7d5e6332b740bb',
    messagingSenderId: '1047069542114',
    projectId: 'tezda-app-afolabi',
    storageBucket: 'tezda-app-afolabi.firebasestorage.app',
    iosBundleId: 'com.afolabi.tezdatask.tezdaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChSXbaNbYK1f1I6gcwQYQH-uzXJTb8p8o',
    appId: '1:1047069542114:ios:c4a6125c7d5e6332b740bb',
    messagingSenderId: '1047069542114',
    projectId: 'tezda-app-afolabi',
    storageBucket: 'tezda-app-afolabi.firebasestorage.app',
    iosBundleId: 'com.afolabi.tezdatask.tezdaTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAulbLvSnDKkcw_wJyqTeiZV7rrghOm4gc',
    appId: '1:1047069542114:web:d651b550f09e5568b740bb',
    messagingSenderId: '1047069542114',
    projectId: 'tezda-app-afolabi',
    authDomain: 'tezda-app-afolabi.firebaseapp.com',
    storageBucket: 'tezda-app-afolabi.firebasestorage.app',
  );
}
